--liquibase formatted sql

--changeset samlien:1
CREATE SCHEMA "budget";

CREATE TABLE "budget"."subject" (
                                    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    "name" varchar(50) NOT NULL,
                                    "created_time" TIMESTAMP NOT NULL,
                                    "created_person" varchar(10) NOT NULL,
                                    "updated_time" TIMESTAMP,
                                    "updated_person" varchar(10)
);

CREATE TABLE "budget"."project" (
                                    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    "name" varchar(200) NOT NULL,
                                    "created_time" TIMESTAMP NOT NULL,
                                    "created_person" varchar(10) NOT NULL,
                                    "updated_time" TIMESTAMP,
                                    "updated_person" varchar(10)
);

CREATE TABLE "budget"."department" (
                                       "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       "name" varchar(10) NOT NULL,
                                       "created_time" TIMESTAMP NOT NULL,
                                       "created_person" varchar(10) NOT NULL,
                                       "updated_time" TIMESTAMP,
                                       "updated_person" varchar(10)
);

CREATE TABLE "budget"."division" (
                                     "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "name" varchar(10) NOT NULL,
                                     "department_id" int NOT NULL,
                                     "created_time" TIMESTAMP NOT NULL,
                                     "created_person" varchar(10) NOT NULL,
                                     "updated_time" TIMESTAMP,
                                     "updated_person" varchar(10)
);

CREATE TABLE "budget"."item" (
                                 "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 "type" varchar(10) NOT NULL,
                                 "subject_id" int NOT NULL,
                                 "project_id" int NOT NULL,
                                 "item_name" varchar(200) NOT NULL,
                                 "population" int,
                                 "note" varchar(100),
                                 "budget" int NOT NULL,
                                 "department_id" int NOT NULL,
                                 "division_id" int NOT NULL,
                                 "created_time" TIMESTAMP NOT NULL,
                                 "created_person" varchar(10) NOT NULL,
                                 "updated_time" TIMESTAMP,
                                 "updated_person" varchar(10)
);

CREATE TABLE "budget"."item_detail" (
                                        "item_id" int,
                                        "type" varchar(10) NOT NULL,
                                        "year" int NOT NULL,
                                        "month" int NOT NULL,
                                        "amount" int NOT NULL,
                                        "created_time" TIMESTAMP NOT NULL,
                                        "created_person" varchar(10) NOT NULL,
                                        "updated_time" TIMESTAMP,
                                        "updated_person" varchar(10),
                                        PRIMARY KEY ("item_id", "type", "year", "month")
);

CREATE TABLE "budget"."transfer" (
                                     "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "transfer_date" date NOT NULL,
                                     "note" varchar(100),
                                     "transfer_out_item_id" int NOT NULL,
                                     "transfer_out_subject_id" int NOT NULL,
                                     "transfer_out_project_id" int NOT NULL,
                                     "transfer_out_department_id" int NOT NULL,
                                     "transfer_out_amount" int NOT NULL,
                                     "transfer_out_remaining_amount" int NOT NULL,
                                     "transfer_in_item_id" int NOT NULL,
                                     "transfer_in_subject_id" int NOT NULL,
                                     "transfer_in_project_id" int NOT NULL,
                                     "transfer_in_department_id" int NOT NULL,
                                     "transfer_in_amount" int NOT NULL,
                                     "transfer_in_remaining_amount" int NOT NULL,
                                     "created_time" TIMESTAMP NOT NULL,
                                     "created_person" varchar(10) NOT NULL,
                                     "updated_time" TIMESTAMP,
                                     "updated_person" varchar(10)
);

ALTER TABLE "budget"."division" ADD FOREIGN KEY ("department_id") REFERENCES "budget"."department" ("id");

ALTER TABLE "budget"."item" ADD FOREIGN KEY ("subject_id") REFERENCES "budget"."subject" ("id");

ALTER TABLE "budget"."item" ADD FOREIGN KEY ("project_id") REFERENCES "budget"."project" ("id");

ALTER TABLE "budget"."item" ADD FOREIGN KEY ("department_id") REFERENCES "budget"."department" ("id");

ALTER TABLE "budget"."item" ADD FOREIGN KEY ("division_id") REFERENCES "budget"."division" ("id");

ALTER TABLE "budget"."item_detail" ADD FOREIGN KEY ("item_id") REFERENCES "budget"."item" ("id");

ALTER TABLE "budget"."transfer" ADD FOREIGN KEY ("transfer_out_item_id") REFERENCES "budget"."item" ("id");

ALTER TABLE "budget"."transfer" ADD FOREIGN KEY ("transfer_out_subject_id") REFERENCES "budget"."subject" ("id");

ALTER TABLE "budget"."transfer" ADD FOREIGN KEY ("transfer_out_project_id") REFERENCES "budget"."project" ("id");

ALTER TABLE "budget"."transfer" ADD FOREIGN KEY ("transfer_out_department_id") REFERENCES "budget"."department" ("id");

ALTER TABLE "budget"."transfer" ADD FOREIGN KEY ("transfer_in_item_id") REFERENCES "budget"."item" ("id");

ALTER TABLE "budget"."transfer" ADD FOREIGN KEY ("transfer_in_subject_id") REFERENCES "budget"."subject" ("id");

ALTER TABLE "budget"."transfer" ADD FOREIGN KEY ("transfer_in_project_id") REFERENCES "budget"."project" ("id");

ALTER TABLE "budget"."transfer" ADD FOREIGN KEY ("transfer_in_department_id") REFERENCES "budget"."department" ("id");
